<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // First, update any existing 'out_of_stock' records to 'critical'
        DB::table('products')
            ->where('status', 'out_of_stock')
            ->update(['status' => 'critical']);

        // PostgreSQL: Drop the old CHECK constraint and add a new one
        // Note: Laravel's enum creates a CHECK constraint in PostgreSQL

        // Get the constraint name (it's auto-generated by Laravel)
        $constraintName = DB::select("
            SELECT constraint_name
            FROM information_schema.constraint_column_usage
            WHERE table_name = 'products'
            AND column_name = 'status'
            AND constraint_name LIKE '%_status_check'
        ");

        if (!empty($constraintName)) {
            $constraint = $constraintName[0]->constraint_name;
            DB::statement("ALTER TABLE products DROP CONSTRAINT {$constraint}");
        }

        // Add new constraint with updated values
        DB::statement("
            ALTER TABLE products
            ADD CONSTRAINT products_status_check
            CHECK (status IN ('in_stock', 'low_stock', 'critical'))
        ");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Drop the new constraint
        DB::statement("ALTER TABLE products DROP CONSTRAINT IF EXISTS products_status_check");

        // Get any existing constraint to drop it
        $constraintName = DB::select("
            SELECT constraint_name
            FROM information_schema.constraint_column_usage
            WHERE table_name = 'products'
            AND column_name = 'status'
            AND constraint_name LIKE '%_status_check'
        ");

        if (!empty($constraintName)) {
            $constraint = $constraintName[0]->constraint_name;
            DB::statement("ALTER TABLE products DROP CONSTRAINT {$constraint}");
        }

        // Restore the old constraint with all four values
        DB::statement("
            ALTER TABLE products
            ADD CONSTRAINT products_status_check
            CHECK (status IN ('in_stock', 'low_stock', 'critical', 'out_of_stock'))
        ");
    }
};
